### ISSUE TITLE
Abnormal raw p-value distribution from aldex.ttest

### ISSUE THREAD

**Issue by ijhoskins** [ggloor/ALDEx2_dev#40]
Hello,

I have been looking at some diagnostic plots of test results and noticed a bimodal raw p-value histogram. 
[aldex_example_pval_distr_gg.pdf](https://github.com/ggloor/ALDEx2_dev/files/11313659/aldex_example_pval_distr_gg.pdf)

For comparison, here is a p-value histogram from a limma analysis, which produces an anti-conservative histogram.
[limma_example_pval_distr_gg.pdf](https://github.com/ggloor/ALDEx2_dev/files/11313556/limma_example_pval_distr_gg.pdf)

http://varianceexplained.org/statistics/interpreting-pvalue-histogram/

I am wondering if such a distribution might be expected given the testing strategy. I tried using a IQLR denominator as well as iterate=TRUE, and I see similar results with different parameters.

Thanks for any help you might be able to provide!

**Comment by ggloor** [comment]
Hi Ian
The P value distribution you see for ALDEx2 is because it is not a p-value, but a posterior p-value (http://www.stat.columbia.edu/~gelman/research/unpublished/ppc_understand2.pdf) which tend towards a value of 0.5 with infinite numbers of dir MC instances. I am updating the documentation to make this clear as it is a common misconception

**Comment by ijhoskins** [comment]
Hi @ggloor thank you for your input, that makes sense!
